# Generated by Django 5.2 on 2025-05-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
