# Generated by Django 5.2 on 2025-05-07 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_sex_student_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
