# Generated by Django 5.2 on 2025-05-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_section_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'description')},
        ),
    ]
