# Generated by Django 5.2 on 2025-05-07 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_section_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'description', 'instructor', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('score', 'student', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'suffix', 'sex')},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('name', 'description', 'total_score', 'course')},
        ),
    ]
