# Generated by Django 5.2 on 2025-05-07 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_course_description_alter_section_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'instructor', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('name', 'total_score', 'course')},
        ),
    ]
