# Generated by Django 5.2 on 2025-05-07 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_course_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z-\\s.]+$', message='Letters and dash only.')]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'suffix', 'sex', 'section')},
        ),
    ]
