# Generated by Django 5.2 on 2025-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_student_unique_together_alter_student_suffix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'suffix', 'sex')},
        ),
    ]
