# Generated by Django 5.2 on 2025-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
