# Generated by Django 5.2 on 2025-05-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_test_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
