# Generated by Django 5.2 on 2025-05-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_test_total_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'test')},
        ),
    ]
