# Generated by Django 5.2 on 2025-05-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_test_pass_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'section')},
        ),
    ]
